ports:
    - port: 3000
      onOpen: open-browser
tasks:
    - init: >
        npm i vercel -g &&
        npm install &&
        cp .env.example .env
      command: >
        npm i vercel -g

vscode:
  extensions:
    - coenraads.bracket-pair-colorizer@1.0.61:fa3401caa00b5b4897921a5ddb2cd8cd